
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN COMMA COMMENT DECIMAL EQUAL HEAD_AND_BODY_SEPARATOR IDENTIFIER INTEGER LEFT_BRACKET NOT_EQUAL QUESTION_MARK RIGHT_BRACKET STRING TILDE VARIABLE\n    program : statement program\n            | statement\n            | empty\n    empty :\n    statement : assertion\n              | retraction\n              | query\n              | requirement\n    \n    assertion : clause DECIMAL\n    \n    retraction : clause TILDE\n    \n    query : literal QUESTION_MARK\n    \n    requirement : LEFT_BRACKET IDENTIFIER RIGHT_BRACKET\n    \n    clause : literal HEAD_AND_BODY_SEPARATOR body\n           | literal\n    \n    body : literal COMMA body\n         | literal\n    \n    literal : predicate LEFT_BRACKET RIGHT_BRACKET\n            | predicate LEFT_BRACKET terms RIGHT_BRACKET\n            | predicate\n            | term EQUAL term\n            | term NOT_EQUAL term\n    \n    predicate : IDENTIFIER\n              | STRING\n    \n    terms : term terms\n          | term\n    \n    term : VARIABLE\n         | constant\n    \n    constant : IDENTIFIER\n             | STRING\n             | INTEGER\n             | BOOLEAN\n    '
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,19,20,21,22,30,],[-4,0,-2,-3,-5,-6,-7,-8,-1,-9,-10,-11,-12,]),'LEFT_BRACKET':([0,2,4,5,6,7,11,12,14,20,21,22,30,],[10,10,-5,-6,-7,-8,-22,25,-23,-9,-10,-11,-12,]),'IDENTIFIER':([0,2,4,5,6,7,10,15,16,17,18,20,21,22,23,25,26,27,30,33,34,35,38,],[11,11,-5,-6,-7,-8,24,-26,-27,-30,-31,-9,-10,-11,11,34,34,34,-12,34,-28,-29,11,]),'STRING':([0,2,4,5,6,7,15,16,17,18,20,21,22,23,25,26,27,30,33,34,35,38,],[14,14,-5,-6,-7,-8,-26,-27,-30,-31,-9,-10,-11,14,35,35,35,-12,35,-28,-29,14,]),'VARIABLE':([0,2,4,5,6,7,15,16,17,18,20,21,22,23,25,26,27,30,33,34,35,38,],[15,15,-5,-6,-7,-8,-26,-27,-30,-31,-9,-10,-11,15,15,15,15,-12,15,-28,-29,15,]),'INTEGER':([0,2,4,5,6,7,15,16,17,18,20,21,22,23,25,26,27,30,33,34,35,38,],[17,17,-5,-6,-7,-8,-26,-27,-30,-31,-9,-10,-11,17,17,17,17,-12,17,-28,-29,17,]),'BOOLEAN':([0,2,4,5,6,7,15,16,17,18,20,21,22,23,25,26,27,30,33,34,35,38,],[18,18,-5,-6,-7,-8,-26,-27,-30,-31,-9,-10,-11,18,18,18,18,-12,18,-28,-29,18,]),'DECIMAL':([8,9,11,12,14,15,16,17,18,28,29,31,34,35,36,37,39,41,],[20,-14,-22,-19,-23,-26,-27,-30,-31,-16,-13,-17,-28,-29,-20,-21,-18,-15,]),'TILDE':([8,9,11,12,14,15,16,17,18,28,29,31,34,35,36,37,39,41,],[21,-14,-22,-19,-23,-26,-27,-30,-31,-16,-13,-17,-28,-29,-20,-21,-18,-15,]),'QUESTION_MARK':([9,11,12,14,15,16,17,18,31,34,35,36,37,39,],[22,-22,-19,-23,-26,-27,-30,-31,-17,-28,-29,-20,-21,-18,]),'HEAD_AND_BODY_SEPARATOR':([9,11,12,14,15,16,17,18,31,34,35,36,37,39,],[23,-22,-19,-23,-26,-27,-30,-31,-17,-28,-29,-20,-21,-18,]),'COMMA':([11,12,14,15,16,17,18,28,31,34,35,36,37,39,],[-22,-19,-23,-26,-27,-30,-31,38,-17,-28,-29,-20,-21,-18,]),'EQUAL':([11,13,14,15,16,17,18,],[-28,26,-29,-26,-27,-30,-31,]),'NOT_EQUAL':([11,13,14,15,16,17,18,],[-28,27,-29,-26,-27,-30,-31,]),'RIGHT_BRACKET':([15,16,17,18,24,25,32,33,34,35,40,],[-26,-27,-30,-31,30,31,39,-25,-28,-29,-24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,2,],[1,19,]),'statement':([0,2,],[2,2,]),'empty':([0,2,],[3,3,]),'assertion':([0,2,],[4,4,]),'retraction':([0,2,],[5,5,]),'query':([0,2,],[6,6,]),'requirement':([0,2,],[7,7,]),'clause':([0,2,],[8,8,]),'literal':([0,2,23,38,],[9,9,28,28,]),'predicate':([0,2,23,38,],[12,12,12,12,]),'term':([0,2,23,25,26,27,33,38,],[13,13,13,33,36,37,33,13,]),'constant':([0,2,23,25,26,27,33,38,],[16,16,16,16,16,16,16,16,]),'body':([23,38,],[29,41,]),'terms':([25,33,],[32,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement program','program',2,'p_program','parser.py',6),
  ('program -> statement','program',1,'p_program','parser.py',7),
  ('program -> empty','program',1,'p_program','parser.py',8),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',18),
  ('statement -> assertion','statement',1,'p_statement','parser.py',23),
  ('statement -> retraction','statement',1,'p_statement','parser.py',24),
  ('statement -> query','statement',1,'p_statement','parser.py',25),
  ('statement -> requirement','statement',1,'p_statement','parser.py',26),
  ('assertion -> clause DECIMAL','assertion',2,'p_assertion','parser.py',32),
  ('retraction -> clause TILDE','retraction',2,'p_retraction','parser.py',38),
  ('query -> literal QUESTION_MARK','query',2,'p_query','parser.py',44),
  ('requirement -> LEFT_BRACKET IDENTIFIER RIGHT_BRACKET','requirement',3,'p_requirement','parser.py',50),
  ('clause -> literal HEAD_AND_BODY_SEPARATOR body','clause',3,'p_clause','parser.py',56),
  ('clause -> literal','clause',1,'p_clause','parser.py',57),
  ('body -> literal COMMA body','body',3,'p_body','parser.py',66),
  ('body -> literal','body',1,'p_body','parser.py',67),
  ('literal -> predicate LEFT_BRACKET RIGHT_BRACKET','literal',3,'p_literal','parser.py',76),
  ('literal -> predicate LEFT_BRACKET terms RIGHT_BRACKET','literal',4,'p_literal','parser.py',77),
  ('literal -> predicate','literal',1,'p_literal','parser.py',78),
  ('literal -> term EQUAL term','literal',3,'p_literal','parser.py',79),
  ('literal -> term NOT_EQUAL term','literal',3,'p_literal','parser.py',80),
  ('predicate -> IDENTIFIER','predicate',1,'p_predicate','parser.py',93),
  ('predicate -> STRING','predicate',1,'p_predicate','parser.py',94),
  ('terms -> term terms','terms',2,'p_terms','parser.py',100),
  ('terms -> term','terms',1,'p_terms','parser.py',101),
  ('term -> VARIABLE','term',1,'p_term','parser.py',110),
  ('term -> constant','term',1,'p_term','parser.py',111),
  ('constant -> IDENTIFIER','constant',1,'p_constant','parser.py',117),
  ('constant -> STRING','constant',1,'p_constant','parser.py',118),
  ('constant -> INTEGER','constant',1,'p_constant','parser.py',119),
  ('constant -> BOOLEAN','constant',1,'p_constant','parser.py',120),
]
